### PR TITLE
Add issue type to API and Opportunities list

### PR DESCRIPTION
**Pull request by marcdel**
Adds issue type to the opportunities list as a first step to implementing the filtering described in https://github.com/elixirschool/extracurricular/issues/65.

### CODE REVIEW

**Comment by marcdel** [comment]
UI is def not my strong suit. If there's a better way to differentiate types from the levels and tags, I'm happy to make changes.

image

**Comment by doomspork** [comment]
This is definitely a change I wanted to make, thanks for taking care of this 👍 

Unfortunately UI/UX isn't my strong suit either 😆 The designer who was helping us has seen stopped so this should do the trick for now.  

I'm hoping to shed some of my work-work and re-focus efforts on moving this project along.  As part of that I am going to reach out to a few design shops about bringing onboard to help with this project and the overall Elixir School brand experience.

**Comment by marcdel** [comment]
Sounds good!

**Review by doomspork — APPROVED** [review]

**Comment by doomspork** [comment]
Thank you again @marcdel!  I'll release this later today 😀 

Do you have a twitter handle?

**Comment by marcdel** [comment]
No problem!

Yup, same as here twitter.com/marcdel

**Pull request merged**
