### PR TITLE
Add Sorting to Opportunities list UI

### PR DESCRIPTION
**Pull request by dberget**
Adding the following functionality for the UI todo on #22. 

@doomspork Let me know what changes are recommended and what tests need to be added. :)

### CODE REVIEW

**Comment by doomspork** [comment]
@dberget you haven't been forgotten about!  I got tied up with some work things and I'm trying to get a basic iteration of Extracurricular deployed so we can iterate on it.  I will get to your PR very soon, thanks for your patience 😁

**Comment by dberget** [comment]
@doomspork oh, no worries! I just didn't want such a simple thing keeping an issue open :)

**Comment by doomspork** [comment]
@dberget could you rebase this?  I think we're good to merge.  After talking to @ybur-yug, he has convinced me that the level of effort to test this would be higher than the implementation itself.  Let's hold off on adding tests until we implement this in the UI and it makes more sense 😁

**Comment by dberget** [comment]
Will do!

**Comment by dberget** [comment]
Should be ready to go :)

**Comment by doomspork** [comment]
Thank you @dberget 👍

**Pull request merged**
